/* Visitatori di Fiera Sicurezza 2019, ordinati per data e cognome */
/* Campi programmabili: Documentazione sì/no, Note aggiuntive */

USE [MRT_SICUREZZA-2019];
GO

DECLARE @DATAINIZIO NVARCHAR(14)
SET @DATAINIZIO='20191113000000'
SELECT 
	(SUBSTRING(T31DATAORAMODIFICA,7,2) + '-' +
	SUBSTRING(T31DATAORAMODIFICA,5,2) + '-' +
	LEFT(T31DATAORAMODIFICA,4) ) AS DATA,
	UPPER(VISITATORI.T31COGNOME) AS COGNOME,
	UPPER(VISITATORI.T31NOME) AS NOME,
	UPPER(VISITATORI.T31SOCIETA) AS AZIENDA,
	VISITATORI.T31MOTIVO AS EMAIL,
	UPPER(VISITATORI.T31EMAIL) AS EMAIL2,
	TIPOVISITA.T124DESCRIZIONE AS TIPOLOGIA,
	DIPENDENTI.T26COGNOME AS [CON CHI HA PARLATO],
	DOCUMENTAZIONE.DESCRIZIONEDOC AS [DOCUMENTAZIONE], -- Campo programmabile Documentazione
	NOTEAGGIUNTIVE.VALORE AS [NOTE AGGIUNTIVE] -- Campo programmabile Note Aggiuntive
FROM T31COMVISITATORI AS VISITATORI
-- Tabella dipendenti
INNER JOIN T26COMDIPENDENTI AS DIPENDENTI
	ON VISITATORI.T31DIPENDENTE=DIPENDENTI.T26CODICE
-- Tabella tipo visite
INNER JOIN T124ACCTIPIVISITE AS TIPOVISITA
	ON VISITATORI.T31TIPOVISITA=TIPOVISITA.T124CODICE
LEFT JOIN (
		--Tabella note aggiuntive
		SELECT 
			T108MATRICOLA AS MATRICOLA,
			T106DESCRIZIONE AS CAMPO,
			T108VALORE AS VALORE,
			T107DESCRIZIONE AS DESCRIZIONEDOC,
			T106FIELDID AS FIELDID
		FROM T108COMDATIAGGIUNTIVI
		INNER JOIN T106COMDEFCAMPIPROGR --Tabella definizione campi programmabili
			ON T108COMDATIAGGIUNTIVI.T108FIELDID=T106COMDEFCAMPIPROGR.T106FIELDID
		LEFT JOIN T107COMDEFSCELTEPROGR --Tabella scelte campi programmabili
			ON T108COMDATIAGGIUNTIVI.T108VALORE=T107COMDEFSCELTEPROGR.T107VALORE
		WHERE T106FIELDID='1' --Note
	) AS NOTEAGGIUNTIVE
	ON VISITATORI.T31CODICE=NOTEAGGIUNTIVE.MATRICOLA
LEFT JOIN (
		--Tabella documentazione
		SELECT 
			T108MATRICOLA AS MATRICOLA,
			T106DESCRIZIONE AS CAMPO,
			T108VALORE AS VALORE,
			T107DESCRIZIONE AS DESCRIZIONEDOC
		FROM T108COMDATIAGGIUNTIVI
		INNER JOIN T106COMDEFCAMPIPROGR --Tabella definizione campi programmabili
			ON T108COMDATIAGGIUNTIVI.T108FIELDID=T106COMDEFCAMPIPROGR.T106FIELDID
		LEFT JOIN T107COMDEFSCELTEPROGR --Tabella scelte campi programmabili
			ON T108COMDATIAGGIUNTIVI.T108VALORE=T107COMDEFSCELTEPROGR.T107VALORE
		WHERE T106FIELDID='2' --Documentazione
		) AS DOCUMENTAZIONE
	ON VISITATORI.T31CODICE=DOCUMENTAZIONE.MATRICOLA
-- Filters
WHERE T31DATAORAMODIFICA >= @DATAINIZIO
AND T31COGNOME <> 'TEST'
-- Order
ORDER BY [DATA],[COGNOME]


