/* It performs a restore of the @DATABASENAME using the @MDFPATH and @LDFPATH read from the backup file in @BACKUPPATH */

DECLARE @DATABASENAME NVARCHAR(20)
DECLARE @BACKUPPATH NVARCHAR(100)
DECLARE @MDFPATH NVARCHAR(255)
DECLARE @LDFPATH NVARCHAR(255)

SET @DATABASENAME = 'MYDATABASENAME'
SET @BACKUPPATH = 'C:\MY\PATH\TO\BAK\FILE.bak'
SET @MDFPATH = 'C:\MY\NEW\PATH\TO\MDF\FILE.mdf'
SET @LDFPATH = 'C:\MY\NEW\PATH\TO\LDF\FILE.ldf'

-- Get logical name
-- A SELECT is possible by using INSERT with the script https://stackoverflow.com/a/4018782
RESTORE FILELISTONLY FROM DISK=@BACKUPPATH WITH FILE=1

-- Restore database
RESTORE DATABASE @DATABASENAME FROM DISK=@BACKUPPATH
WITH 
MOVE [YOUR_DATA_LOGICAL_NAME] TO @MDFPATH,
MOVE [YOUR_LOG_LOGICAL_NAME] TO @LDFPATH,
RECOVERY, REPLACE, STATS = 10;
