/* MRT_Get-EnabledOnGates.sql
/*
/* Restituisce CodVarco,DescrVarco,NumMatricole */
/* Dove NumMatricole è il totale delle matricole, tra quelle inserite nel range T35CODICE IN (), abilitate sul varco in questione
*/

SELECT 
  CODVARCO, 
  T23DESCRIZIONE AS DESCRVARCO, 
  COUNT(*) AS N 
FROM (
  SELECT 
    T35VARCO AS CODVARCO 
  FROM T35ACCPROFILIORARI 
  WHERE T35FLAGGRUPPO='0' 
    AND T35TIPOCODICE='0' 
    AND T35CODICE IN ('00000001', '00000002') -- Insert list here
UNION ALL
SELECT 
  T40VARCO AS CODVARCO
FROM T35ACCPROFILIORARI P
INNER JOIN T40ACCDGRUPPIVARCHI D
  ON P.T35GRUPPO=D.T40GRUPPO
WHERE T35FLAGGRUPPO='1' 
  AND T35TIPOCODICE='0' 
  AND T35CODICE IN ('00000001', '00000002')) R
INNER JOIN T23ACCVARCHI V
  ON (R.CODVARCO=V.T23CODICE)
GROUP BY CODVARCO, T23DESCRIZIONE

/* Esempio:
/* CodVarco | DescrVarco | N
/* 0000001 | Main Gate | 15
