-- CERCA ABILITAZIONI
-- Ricevendo come input il codice del varco, 
-- estrae i gruppi di varchi che contengono quel varco 
-- e le abilitazioni di tutti i tipi di matricola

USE MRT
-- Varco da cercare
DECLARE @VARCO NVARCHAR(8)
SET @VARCO='00001833'
-- Gruppi di varchi che includono il varco in questione
SELECT DISTINCT T40GRUPPO AS CodiceGruppoVarchi,T27DESCRIZIONE AS DescrizioneGruppoVarchi
FROM T40ACCDGRUPPIVARCHI 
INNER JOIN T27ACCTGRUPPIVARCHI ON T40GRUPPO=T27CODICE
WHERE T40VARCO=@VARCO
-- Gruppi di dipendenti abilitati al varco o ai gruppi di varchi selezionati
SELECT DISTINCT 
	T35CODICE AS CODICE, 
	CASE T35TIPOCODICE 
		WHEN 0 THEN 'DIPENDENTE'
		WHEN 1 THEN 'COLLABORATORE ESTERNO'
		WHEN 2 THEN 'VISITATORE'
		WHEN 8 THEN 'GRUPPO DI DIPENDENTI'
		WHEN 9 THEN 'AZIENDA ESTERNA'
		END AS TIPO,
	T35VARCO AS VARCO,
	T35GRUPPO AS [GRUPPO DI VARCHI],
	CASE T35FLAGNORMALE
		WHEN 1 THEN 'ABIL.ECCEZ.'
		END AS TIPOABILITAZIONE
FROM T35ACCPROFILIORARI
WHERE (T35VARCO=@VARCO
OR T35GRUPPO IN (
	SELECT DISTINCT T40GRUPPO 
	FROM T40ACCDGRUPPIVARCHI 
	WHERE T40VARCO=@VARCO)
)
