/* Vista logica per stampa badge con campi programmabili */

-- Vista logica da usare per il software di stampa dei badge.
-- Sono gestiti i campi programmabili a scelta singola (TIPO LAYOUT, selezionabile tra 'Nome esteso' o 'Cognome esteso') e testo libero (QUALIFICA STAMPA).

SELECT 
	RIGHT(DIP.T26CODICE,5) AS MATRICOLA,
	DIP.T26COGNOME AS COGNOME,
	DIP.T26NOME AS NOME,
	CASE TIPOLAYOUT.DESCRIZIONELAYOUT
		WHEN 'NOME ESTESO' THEN DIP.T26NOME + ' ' + LEFT(DIP.T26COGNOME,1) + '.' 	-- Mario R.
		WHEN 'COGNOME ESTESO' THEN LEFT(DIP.T26NOME,1) + '. ' + DIP.T26COGNOME		-- M. Rossi
		END
	AS [COGNOME E NOME],
	DIP.T26FOTO AS FOTO,
	DIP.T26BADGEATTIVO AS BADGE,
	CAST(RUOLI.RUOLO AS VARCHAR(200)) AS QUALIFICASTAMPA,
	DIP.T26CODAZIENDA AS CODICEAZIENDAINTERNA,
	AZ.T71DESCRAZIENDA AS DESCRAZIENDAINTERNA,
	B.T25DESCRIZIONE AS DATAORASTAMPA,
	B.T25ID0 AS BANDAMAGNETICA,
	B.T25ID1 AS TAGRFID,
	TIPOLAYOUT.DESCRIZIONELAYOUT AS DESCRIZIONELAYOUT	-- Tipo layout ('Nome esteso' o 'Cognome esteso')
FROM T26COMDIPENDENTI AS DIP
INNER JOIN T71COMAZIENDEINTERNE AS AZ
	ON DIP.T26CODAZIENDA = AZ.T71CODICE
INNER JOIN T25COMBADGE AS B
	ON DIP.T26BADGEATTIVO = B.T25CODICE
INNER JOIN (
  /* Tabella layout */
  SELECT 
    DATI.T108MATRICOLA AS MATRICOLA,
    DATI.T108AZIE AS AZIENDA,
    DATI.T108VALORE AS VALORELAYOUT,
    SCELTE.T107DESCRIZIONE AS DESCRIZIONELAYOUT
  FROM T108COMDATIAGGIUNTIVI AS DATI
  INNER JOIN T107COMDEFSCELTEPROGR AS SCELTE
    ON DATI.T108VALORE = SCELTE.T107VALORE
  WHERE DATI.T108TIPOMATRICOLA='0' AND DATI.T108FIELDID='1'
  ) AS TIPOLAYOUT
	ON DIP.T26CODICE = TIPOLAYOUT.MATRICOLA AND DIP.T26CODAZIENDA = TIPOLAYOUT.AZIENDA
INNER JOIN (
  /* Tabella ruoli */
  SELECT 
    DATI_1.T108MATRICOLA AS MATRICOLA,
    DATI_1.T108AZIE AS AZIENDA,
    DATI_1.T108VALORE AS RUOLO
  FROM T108COMDATIAGGIUNTIVI AS DATI_1
  WHERE DATI_1.T108TIPOMATRICOLA='0' AND DATI_1.T108FIELDID='2'
  ) AS RUOLI
	ON DIP.T26CODICE = RUOLI.MATRICOLA AND DIP.T26CODAZIENDA = RUOLI.AZIENDA;
