/* MRT_Select-EmployeesBadge-ColoreQualifica.sql
/*
/* Vista logica dipendenti con campi programmabili, per stampa badge
/* La vista seleziona, oltre ai soliti dati per stampa badge, anche i campi programmabili COLORE (Field=1) e QUALIFICA (Field=2)
*/

SELECT
  RIGHT(D.T26CODICE,6) AS MATRICOLA,
  D.T26NOME AS NOME,
  D.T26COGNOME AS COGNOME,
  RIGHT(D.T26BADGEATTIVO,5) AS BADGEATTIVO,
  D.T26FOTO AS FOTO,
  D.T26CODAZIENDA AS CODAZIENDAINTERNA,
  A.T71DESCRAZIENDA AS DESCRAZIENDAINTERNA,
  B.T25DESCRIZIONE AS DATAORASTAMPA,
  RIGHT(B.T25ID0,5) AS IDMAGNETICO,
  B.T25ID1 AS RFID,
  QUALIFICHE.QUALIFICADIPENDENTE AS QUALIFICA,
  COLORI.COLOREDIPENDENTE AS COLORE,
  LEFT(D.T26NOME,1) AS INIZIALENOME
FROM T71COMAZIENDEINTERNE AS A
INNER JOIN T26COMDIPENDENTI AS D
  ON A.T71CODICE = D.T26CODAZIENDA
INNER JOIN T25COMBADGE AS B
  ON D.T26BADGEATTIVO = B.T25CODICE
INNER JOIN 
  /* Tabella colori */
  (SELECT
    T108MATRICOLA AS MATRICOLA,
    T108AZIE AS AZIENDA,
    T108VALORE AS COLOREDIPENDENTE,
   FROM T108COMDATIAGGIUNTIVI
   WHERE (
    T108TIPOMATRICOLA='0' --Dipendenti
    AND T108FIELDID='1' --Colore
    ) AS COLORI
  ON D.T26CODICE=COLORI.MATRICOLA AND D.T26CODAZIENDA=COLORI.AZIENDA
INNER JOIN
  /* Tabella qualifiche */
  (SELECT
    T108MATRICOLA AS MATRICOLA,
    T108AZIENDA AS AZIENDA,
    T108VALORE AS QUALIFICADIPENDENTE
   FROM T108COMDATIAGGIUNTIVI AS T108COMDATIAGGIUNTIVI_1
   WHERE (
    T108TIPOMATRICOLA='0' --Dipendenti
    AND T108FIELDID='2' --Qualifica
    ) AS QUALIFICHE
  ON D.T26CODICE=QUALIFICHE.MATRICOLA AND D.T26CODAZIENDA=QUALIFICHE.AZIENDA
