/* MRT_Select-ReportsAuthorizations.sql
/*
/* It returns a table containing USER;FLAGUSER;DESCRIPTION;CANMODIFY;CANUSE for the reports table */

SELECT 
	T21UTENTE AS Username, 
	'Utente' AS FLAGUTENTE, 
	T43DESCRIZIONE AS DESCRIZIONE, 
	T53CANMODIFY AS MODIFICA, 
	T53CANUSE AS USO 
FROM T21COMUTENTI U
INNER JOIN 
	(
		SELECT 
			T53FILENAME, 
			T53CANMODIFY, 
			T53CANUSE, 
			T53UTENTE 
		FROM T53COMAUTSTAMPE WHERE T53FLAGGRUPPO='0'
	) US
	ON U.T21UTENTE=US.T53UTENTE
INNER JOIN T43COMREPORTS R
	ON US.T53FILENAME=R.T43FILENAME
UNION ALL
SELECT 
	T21UTENTE AS Username, 
	'Utente' AS FLAGUTENTE, 
	T43DESCRIZIONE AS DESCRIZIONE, 
	'1' AS MODIFICA, 
	'1' AS USO 
FROM T21COMUTENTI u
LEFT JOIN 
	(
		SELECT 
			T53FILENAME, 
			T53UTENTE 
		FROM T53COMAUTSTAMPE 
		WHERE T53FLAGGRUPPO='0'
	) US
	ON U.T21UTENTE=US.T53UTENTE
CROSS JOIN T43COMREPORTS R
WHERE T53FILENAME IS NULL 
/* Exceptions for customer customizations
AND T43FILENAME NOT IN ('rlabadge.rpt', 'rlfbadge.rpt', 'rlsbadge.rpt', 'rltbadge.rpt', 'rlstvis.rpt', 'rlinde.rpt', 
'rltrans.rpt', 'sietrans.rpt', 'sietranf.rpt', 'aguregv.rpt', 'sgiorgio.rpt', 'diarios.rpt', 'pfizercm.rpt')
*/
UNION ALL
SELECT 
	T95CODICE AS Username, 
	'Gruppo' AS FLAGUTENTE, 
	T43DESCRIZIONE AS DESCRIZIONE, 
	T53CANMODIFY AS MODIFICA, 
	T53CANUSE AS USO 
FROM T95COMGRUPPIUTENTI U
INNER JOIN 
	(
		SELECT 
			T53FILENAME, 
			T53CANMODIFY, 
			T53CANUSE, 
			T53UTENTE 
		FROM T53COMAUTSTAMPE 
		WHERE T53FLAGGRUPPO='1'
	) US
	ON U.T95CODICE=US.T53UTENTE
INNER JOIN T43COMREPORTS R
	ON US.T53FILENAME=R.T43FILENAME
UNION ALL
SELECT 
	T95CODICE AS Username, 
	'Gruppo' AS FLAGUTENTE, 
	T43DESCRIZIONE AS DESCRIZIONE, 
	'1' AS MODIFICA, 
	'1' AS USO 
FROM T95COMGRUPPIUTENTI U
LEFT JOIN 
	(
		SELECT 
			T53FILENAME, 
			T53UTENTE 
		FROM T53COMAUTSTAMPE 
		WHERE T53FLAGGRUPPO='1'
	) US
	ON U.T95CODICE=US.T53UTENTE
CROSS JOIN T43COMREPORTS R
WHERE T53FILENAME IS NULL 
/* Exceptions for customer customizations
AND T43FILENAME NOT IN ('rlabadge.rpt', 'rlfbadge.rpt', 'rlsbadge.rpt', 'rltbadge.rpt', 'rlstvis.rpt', 'rlinde.rpt', 
'rltrans.rpt', 'sietrans.rpt', 'sietranf.rpt', 'aguregv.rpt', 'sgiorgio.rpt', 'diarios.rpt', 'pfizercm.rpt')
*/
ORDER BY USERNAME, FLAGUTENTE, DESCRIZIONE


