/* Query to cross data from table T128COMTMAIL (mail log), T105COMUSERLOG (users log) and T37ACCTRANSITI (transits log) */
/* Helpful in troubleshooting the Notifier procedure */
/* Requires the following variables */

/* Declaring variables */
DECLARE @DATAORAINIZIO nvarchar(14)
DECLARE @DATAORAFINE nvarchar(14)
DECLARE @COGNOMEVISITATORE nvarchar(40)
DECLARE @NOMEVISITATORE nvarchar(40)
DECLARE @BADGEID nvarchar(10)

/* Set variables */
SET @DATAORAINIZIO = '20200212000000'
SET @DATAORAFINE = '20200212235959'
SET @COGNOMEVISITATORE = 'BORGNA'
SET @NOMEVISITATORE = 'MARIA IMMACOLATA'
SET @BADGEID = '9900115401'


USE MRT 
/* Mail inviate */
SELECT 
	T128DATE AS DATAORA,
	'Mail inviata a ' + T128MAILTO + ' con oggetto: ' + T128SUBJECT as EVENTO
FROM T128COMTMAIL
WHERE T128DATE BETWEEN @DATAORAINIZIO AND @DATAORAFINE
AND (T128SUBJECT LIKE '%@BADGEID%' OR T128SUBJECT LIKE '%@COGNOMEVISITATORE%')
UNION ALL
/* Log utenti */
SELECT 
	T105DATAORA AS DATAORA,
	T105DESCRIZIONE AS EVENTO
FROM T105COMUSERSLOG WHERE 
(T105DATAORA BETWEEN @DATAORAINIZIO AND @DATAORAFINE) AND 
(T105DESCRIZIONE LIKE '%@COGNOMEVISITATORE%' OR T105DESCRIZIONE LIKE '%@BADGE%')
UNION ALL
/* Transiti */
SELECT 
	T37DATAORA AS DATAORA,
	CASE 
		WHEN T37ENTRAESCE = 1 THEN 'Transito in ingresso da parte di ' + T37MATRICOLA + ' ' + T37COGNOME + ' ' + T37NOME + ' sul varco ' + T37VARCO 
		WHEN T37ENTRAESCE = 1 THEN 'Transito in uscita da parte di ' + T37MATRICOLA + ' ' + T37COGNOME + ' ' + T37NOME + ' sul varco ' + T37VARCO 
	end
	AS EVENTO

FROM T37ACCTRANSITI WHERE T37DATAORA BETWEEN @DATAORAINIZIO AND @DATAORAFINE
AND (T37COGNOME LIKE '%@COGNOMEVISITATORE%' AND T37NOME LIKE '%@NOMEVISITATORE%')
/* Ordine cronologico */
ORDER BY DATAORA ASC
